name: CD
on:
  push:
    branches:
      - master
jobs:
  cd:
    name: Build & Push GitHub Package & Deploy on Render Docker Image
    runs-on: ubuntu-22.04
    steps:
      - name: clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Get version from package.json
        id: get-version
        # REPOSITORY: nombre del repositorio
        # PACKAGE_PATH: ruta de los paquetes de destino
        # VERSION: versión sacado del fichero POM
        run: |
          echo "REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
          echo "VERSION=$(node -pe "require('./package.json').version")" >> $GITHUB_ENV
          echo "PACKAGE_PATH=ghcr.io/${{ github.repository }}" >> $GITHUB_ENV

      - name: Build Angular app
        run: npm run build-prod

      - name: Upload build to AWS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_LIGHTSAIL_IP }}
          username: ${{ secrets.AWS_LIGHTSAIL_USER }}
          port: 22 # SSH
          key: ${{ secrets.AWS_LIGHTSAIL_SSH_KEY }}
          source: "dist/goa-front/**"
          target: "~/goa-front"

      - name: Deploy frontend on Nginx (AWS)
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.AWS_LIGHTSAIL_IP }}
          username: ${{ secrets.AWS_LIGHTSAIL_USER }}
          port: 22
          key: ${{ secrets.AWS_LIGHTSAIL_SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/goa-front
            sudo rm -rf /var/www/goa-front/*
            sudo cp -r ~/goa-front-temp/* /var/www/goa-front/
            sudo rm -rf ~/goa-front-temp
            sudo systemctl reload nginx
