name: CI
on:
  push:
    branches: [ develop,release-* ]
jobs:
  ci:
    name: Test - Unit & Integration & SonarCloud Scan
    runs-on: ubuntu-22.04
    steps:
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run-script build-prod  # package.json -> "scripts"

      - name: SonarCloud Scan
        if: success()
        uses: SonarSource/sonarcloud-github-action@v5 # file: sonar-project.properties
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
